import { CardGame } from "@/components/CardGame";
import Head from "next/head";
import { useCountdown } from "usehooks-ts";
import { clsx } from "clsx";
import { useState } from "react";

export default function Game() {
  const [count, { startCountdown, stopCountdown, resetCountdown }] =
    useCountdown({
      countStart: 100,
      intervalMs: 1000,
    });

  const [flips, setFlips] = useState<number>(1);
  const [score, setScore] = useState<number>(0);

  return (
    <div className=" w-screen h-screen overflow-hidden">
      <Head>
        <title>Memory Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {count === 0 ||
          score === 7 ||
          (count === 0 && score >= 5 && flips <= 30) ||
          flips > 30 ||
          (score >= 5 && flips <= 30) ? (
            <div
              onAnimationStart={stopCountdown}
              className="bg-teal-900 flex justify-center items-center py-80"
            >
              <div>
                <h1
                  className={clsx(
                    "text-9xl  uppercase text-red-700 font-extrabold mb-16 text-center blink",
                    { "text-yellow-500": score >= 5 && flips <= 30 }
                  )}
                >
                  {score >= 5 && flips <= 30 ? "You Win 🏆" : "Game Over"}
                </h1>
                <div
                  className={clsx(
                    "text-5xl text-red-700  font-extrabold text-center  ",
                    {
                      "text-yellow-500": score >= 5 && flips <= 30,
                    }
                  )}
                >
                  <h2 className="mb-4"> Score : {score} </h2>
                  <h2 className="mb-4"> Flips : {flips - 1}</h2>
                  <h2>Time : {count}</h2>
                </div>
              </div>
            </div>
          ) : (
            <div
              onClick={startCountdown}
              className=" bg-teal-400 flex justify-center items-center  py-14"
            >
              <div>
                <h1 className="text-7xl text-yellow-300 font-extrabold mb-16 text-center">
                  Memory Game 🧠
                </h1>
                <div className="grid grid-cols-3  mb-4">
                  <div
                    className={clsx(
                      "flex gap-4 font-bold ",
                      {
                        "text-yellow-300 text-3xl": count >= 10,
                      },
                      {
                        "text-red-700 text-5xl blink": count < 10,
                      }
                    )}
                  >
                    <h2>Time :</h2>
                    <div>{count}</div>
                  </div>

                  <h2 className="text-3xl text-yellow-300 font-bold text-center">
                    Score : {score}
                  </h2>

                  <h2 className="text-3xl text-yellow-300 font-bold ml-auto">
                    Flips : {flips - 1}
                  </h2>
                </div>
                <CardGame
                  flips={flips}
                  setFlips={() => setFlips(flips + 1)}
                  score={score}
                  setScore={() => setScore(score + 1)}
                />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
