import { CardGame } from "@/components/CardGame";
import Head from "next/head";
import { useCountdown } from "usehooks-ts";
import { clsx } from "clsx";

export default function Home() {
  const [count, { startCountdown, stopCountdown, resetCountdown }] =
    useCountdown({
      countStart: 100,
      intervalMs: 1000,
    });
  return (
    <div
      onClick={startCountdown}
      className=" bg-blue-600 overflow-hidden w-screen h-screen"
    >
      <Head>
        <title>Memory Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center  py-14">
        <div>
          <h1 className="text-7xl text-orange-600 font-extrabold mb-16 text-center">
            Memory Game 🧠
          </h1>
          <div className="flex mb-4">
            <div
              className={clsx(
                "flex gap-4 font-bold",
                {
                  "text-yellow-200 text-3xl": count >= 10,
                },
                {
                  "text-red-700 text-5xl blink": count < 10,
                }
              )}
            >
              <h2>Time :</h2>
              <div>{count}</div>
            </div>

            <h2 className="text-3xl text-yellow-200 font-bold ml-auto">
              Flips :
            </h2>
          </div>
          <CardGame />
        </div>
      </div>
    </div>
  );
}
