import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const router = useRouter();
  const level = router.query.level as string;
  const [audio, setAudio] = useState<boolean | undefined>(false);
  return (
    <div className=" w-screen h-screen overflow-hidden">
      <Head>
        <title>Memory Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-r bg-teal-400 w-screen min-h-screen h-full">
        {level === "" ? (
          <main className="p-8">
            <h1 className="text-5xl text-shadow text-yellow-300 font-extrabold text-center">
              Select Level
            </h1>
            <hr className="my-8 opacity-40"></hr>
            <div className="w-full mt-20 grid gap-4  place-items-center container mx-auto grid-cols-1">
              <a
                role="button"
                className="w-1/2 text-shadow  bg-gradient-to-tl bg-teal-300 text-center flex justify-center items-center h-20 text-yellow-50 rounded-md transform transition text-lg duration-100 hover:text-yellow-300 font-bold shadow-lg"
                href={`/game?level=easy`}
              >
                Easy
              </a>
              <a
                role="button"
                className="w-1/2 text-shadow  bg-gradient-to-tl bg-teal-300  text-center flex justify-center items-center h-20 text-yellow-50 rounded-md transform transition text-lg duration-100 hover:text-yellow-300 font-bold shadow-lg"
                href={`/game?level=medium`}
              >
                Medium
              </a>
              <a
                role="button"
                className="w-1/2 text-shadow  bg-gradient-to-tl bg-teal-300  text-center flex justify-center items-center h-20 text-yellow-50 rounded-md transform transition text-lg duration-100 hover:text-yellow-300 font-bold shadow-lg"
                href={`/game?level=hard`}
              >
                Hard
              </a>
            </div>
          </main>
        ) : (
          <main className="p-8">
            <h1 className="text-5xl text-shadow text-yellow-300 font-extrabold text-center">
              Memory Game
            </h1>
            <hr className="my-8 opacity-40"></hr>
            <div className="w-full mt-20 grid gap-4  place-items-center container mx-auto grid-cols-1">
              <a
                role="button"
                className="w-1/2 text-shadow  bg-gradient-to-tl bg-teal-300 text-center flex justify-center items-center h-20 text-yellow-50 rounded-md transform transition text-lg duration-100 hover:text-yellow-300 font-bold shadow-lg"
                href={`/?level`}
                onClick={() => console.log(router.pathname)}
              >
                Start Game
              </a>
              <a
                role="button"
                className="w-1/2 text-shadow  bg-gradient-to-tl bg-teal-300  text-center flex justify-center items-center h-20 text-yellow-50 rounded-md transform transition text-lg duration-100 hover:text-yellow-300 font-bold shadow-lg"
                onClick={() => setAudio(!audio)}
              >
                {audio ? "Audio on" : "Audio off"}
              </a>
            </div>
          </main>
        )}
      </div>
    </div>
  );
}
